### PR TITLE
random entries to supply room

### PR DESCRIPTION
**Pull request by dice4321**
Has a 80% chance to enter a random room when supplying

### CODE REVIEW

**Comment by dice4321** [comment]
I tried to a new function to house this random room entry, but when I do that, the clickS stops working

**Comment by Ryuuhou** [comment]
Sorry, I am not sure if this works or if it is even needed.  I'm guessing you're trying to avoid anti-bot?

**Comment by dice4321** [comment]
Indeed, this is just a precautionary measure against the ban hammer. The red hp checker works sometimes only, i need to look into that hmmmmmmmm.

**Comment by dice4321** [comment]
hp checker needs fixin

**Pull request closed without merging**
